### PR TITLE
patch updating `__site/`

### PR DESCRIPTION
**Pull request by burtonjosh**
The changes in the previous merge didn't update the site, since the changes made to the `__site/` folder weren't included.

This push just contains the content that got modified from the previous PR :)

@bschne I think you need to run `using Franklin; serve()` in order to update the contents of this folder and then push them. Not sure without looking into it if there is a way to automate this process through actions.

### CODE REVIEW

**Comment by bschne** [comment]
That's odd, you'd usually want to gitignore the build/output folder with static site generators and then re-build from source in the build & deploy action and deploy that thing.

We have this in our github actions which should run a build and then push the __site folder _from that build_ to gh pages:

https://github.com/cpfiffer/julia-deeplearning/blob/0ca086ad3bd6db1d67fd796cd86dda46c72d0da2/.github/workflows/Deploy.yml#L37C5-L47C23

**Comment by burtonjosh** [comment]
Yeah you're right. Not sure why the new content is not showing on the site then, unless it's taking ages to update?

This is mentioned on the Franklin docs and could potentially have been missed out @cpfiffer ?:

> The final step is to tell GitHub to deploy the `gh-pages` branch, for this, on the repository go to Settings then scroll down to GitHub Pages and in the Source dropdown, pick `gh-pages`.

**Comment by just-cameron** [comment]
We're currently building it from `gh-pages`, at least that's what it's telling us. The `gh-pages` branch has some missing stuff though, which may or may not be a result of having `__site` dragged around. #8 should help?

image

**Comment by just-cameron** [comment]
I'll close this for now since we ultimately don't want this directory in here.

**Pull request closed without merging**
